version: "3"

services:
  fast-api:
    build: .
    container_name: fast-api
    ports:
      - "8000:8000"
    networks:
      - back-tier

  mypostgres:
    image: postgres
    container_name: mypostgres
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "suphanice"
      POSTGRES_DB: "dev"
    ports:
      - "5432:5432"
    networks:
      - back-tier

networks:
  back-tier:
